views/attend.py
from flask import Blueprint, render_template, request, current_app, url_for, session, redirect, flash
from datetime import datetime, timedelta
import requests

attend_bp = Blueprint('attend', __name__)

def checkTag(tag_id):
    ATLAS_API_URL = current_app.config['ATLAS_API_URL']
    database_name = current_app.config['DATABASE_NAME']
    collection_name = current_app.config['COLLECTION_NAME']
    headers = current_app.config['HEADERS']
    
    try:
        response = requests.post(
            f"{ATLAS_API_URL}/action/findOne",
            headers=headers,
            json={
                "database": database_name,
                "collection": collection_name,
                "dataSource": "Cluster0",
                "filter": {"tag_id": tag_id}
            }
        )
        response.raise_for_status()  # an exception for 4xx and 5xx status codes

        tag_id = response.json().get('document', {})
        if tag_id is None:
            return None
        return tag_id

    except requests.RequestException as e:
        flash(f"Error checking tag: {str(e)}", 'danger')
        return None
def checkExist(tag_id):
    ATLAS_API_URL = current_app.config['ATLAS_API_URL']
    database_name = current_app.config['DATABASE_NAME']
    collection_name = current_app.config['COLLECTION_NAME']
    headers = current_app.config['HEADERS']
    today_start = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
    today_end = today_start + timedelta(days=1)
    response = requests.post(
        f"{ATLAS_API_URL}/action/findOne",
        headers=headers,
        json={
            "database": database_name,
            "collection": "attendance",
            "dataSource": "Cluster0",
            "filter": {
                "tag_id": tag_id,
                "attendance_time": {
                    "$gte": today_start.strftime("%Y-%m-%d %H:%M:%S"),
                    "$lt": today_end.strftime("%Y-%m-%d %H:%M:%S")
                }
            }
        }
    )

    tag_id = response.json().get('document', {})
    if tag_id is None:
        return None
    return tag_id

def recordAttendance(tag_id):
    ATLAS_API_URL = current_app.config['ATLAS_API_URL']
    database_name = current_app.config['DATABASE_NAME']
    headers = current_app.config['HEADERS']
    try:
        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        insert_payload = {
            "dataSource": "Cluster0",
            "database": database_name,
            "collection": "attendance",
            "document": {
                "tag_id": tag_id,
                "attendance_time": current_time,
            }
        }

        insert_response = requests.post(
            f"{ATLAS_API_URL}/action/insertOne",
            headers=headers,
            json=insert_payload
        )
        insert_response.raise_for_status()

        if insert_response.status_code == 201:
            flash('This student attended successfully.', 'success')
            return True
        else:
            flash(f"Error recording attendance: {insert_response.status_code}, {insert_response.text}", 'danger')
            return False

    except requests.RequestException as e:
        flash(f"Error recording attendance: {str(e)}", 'danger')
        return False

@attend_bp.route('/attend', methods=['GET', 'POST'])
def attend():
    if 'username' in session:
        if request.method == 'POST' and request.form.get('tag_data'):
            tag_id = request.form.get('tag_data')
            if checkExist(tag_id) is not None:
                flash('This student is Already attended', 'danger')
                return render_template('attend.html')
            student_info = checkTag(tag_id)

            if student_info is None:
                flash('No student found with this tag.', 'danger')
            else:
                if recordAttendance(tag_id):
                    return render_template('attend.html')

        return render_template('attend.html')

    return redirect(url_for('auth.login'))

views/auth.py
from flask import Flask, render_template, request, redirect, url_for, session, Blueprint, current_app,flash
from flask_pymongo import PyMongo
from werkzeug.security import generate_password_hash, check_password_hash
import requests


auth_bp = Blueprint('auth', __name__)
# mongo = PyMongo()
@auth_bp.route('/', methods=['GET', 'POST'])
def login():
    ATLAS_API_URL = current_app.config['ATLAS_API_URL']
    database_name = current_app.config['DATABASE_NAME']
    headers = current_app.config['HEADERS']

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        # Payload for MongoDB API request (findOne)
        find_payload = {
            "dataSource": "Cluster0",
            "database": database_name,
            "collection": "users",
            "filter": {"username": username}
        }

        # Find user in the MongoDB collection
        response = requests.post(
            f"{ATLAS_API_URL}/action/findOne",
            headers=headers,
            json=find_payload
        )

        if response.status_code == 200:
            user = response.json().get('document',{})
            if user and check_password_hash(user['password'], password):
                session['username'] = username
                return redirect(url_for('dashboard.dashboard'))
            else:
                flash('Invalid username or password', 'error')
        else:
            flash('Error connecting to MongoDB API', 'error')

    return render_template('login.html')

# Logout
@auth_bp.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('auth.login'))

views/set_data.py
from flask import Blueprint, render_template, request,current_app,url_for, session, redirect
from datetime import datetime
from werkzeug.utils import secure_filename
import requests
import os

set_data_bp = Blueprint('set_data', __name__)
@set_data_bp.route('/set-data', methods=['GET', 'POST'])
def set_data():
    if 'username' in session:
        ATLAS_API_URL = current_app.config['ATLAS_API_URL']
        database_name = current_app.config['DATABASE_NAME']
        collection_name = current_app.config['COLLECTION_NAME']
        headers = current_app.config['HEADERS']
        if request.method == 'POST' and request.form.get('student_id') and request.form.get('name'):
            # Process the form data and store it in MongoDB Atlas
            student_id = request.form.get('student_id')
            name = request.form.get('name')
            gender = request.form.get('gender')
            student_image = request.files['student_image']
            # Simulate RFID tag data
            tag_id = request.form.get('tag_id')
            if not student_image or not allowed_file(student_image.filename):
                filename="student_avatar.png"
            if student_image and allowed_file(student_image.filename):
                filename = secure_filename(student_image.filename)
                image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                student_image.save(image_path)



            # Get the current date and time
            current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

            # Payload for MongoDB API request (insert)
            insert_payload = {
                "dataSource": "Cluster0",
                "database": database_name,
                "collection": collection_name,
                "document": {
                    "tag_id": tag_id,
                    "user_name": name,
                    "student_id": student_id,
                    "student_image": filename,
                    "gender": gender,
                    "registered_time": current_time,
                }
            }

            # Insert attendance record
            insert_response = requests.post(
                f"{ATLAS_API_URL}/action/insertOne",
                headers=headers,
                json=insert_payload
            )

            if insert_response.status_code == 201:
                inserted_id = insert_response.json().get("insertedId")
                print("Successfully recorded attendance for user:", name)
                print("Inserted document ID:", inserted_id)
                print("RFID Tag Data:", tag_id)

                return render_template('set_data.html')
            else:
                return f"Error recording attendance: {insert_response.status_code}, {insert_response.text}"

        # Render the form page for GET requests
        return render_template('set_data.html')
    return redirect(url_for('auth.login'))

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

views/students.py
from flask import Blueprint, render_template, request, current_app, abort,url_for, session, redirect, Response, flash
import requests
from reportlab.pdfgen import canvas
from io import BytesIO
from werkzeug.utils import secure_filename
import os
students_bp = Blueprint('students', __name__)
#Just A Global Variable
student_data = 0
@students_bp.route('/students')
def display_students():
    if 'username' in session:
        ATLAS_API_URL = current_app.config['ATLAS_API_URL']
        database_name = current_app.config['DATABASE_NAME']
        collection_name = current_app.config['COLLECTION_NAME']
        headers = current_app.config['HEADERS']

        response = requests.post(
            f"{ATLAS_API_URL}/action/find",
            headers=headers,
            json={
                "database": database_name,
                "collection": collection_name,
                "dataSource": "Cluster0",
            }
        )
        if response.status_code == 200:
            global student_data
            student_data = response.json().get('documents', [])
            return render_template('students.html', data=student_data)
        else:
            return f"Error fetching attendance data. Status code: {response.status_code}"
    return redirect(url_for('auth.login'))

@students_bp.route('/students/edit/<string:student_id>',methods=['GET', 'POST'])
def update_data(student_id):
    if 'username' in session:
        ATLAS_API_URL = current_app.config['ATLAS_API_URL']
        database_name = current_app.config['DATABASE_NAME']
        collection_name = current_app.config['COLLECTION_NAME']
        headers = current_app.config['HEADERS']

        # Fetch existing student data from MongoDB
        fetch_payload = {
            "dataSource": "Cluster0",
            "database": database_name,
            "collection": collection_name,
            "filter": {"student_id": student_id}
        }

        fetch_response = requests.post(
            f"{ATLAS_API_URL}/action/find",
            headers=headers,
            json=fetch_payload
        )
        studentdata = None 
        if fetch_response.status_code == 200:
            studentdata = fetch_response.json()
            if request.method == 'POST':
                # Process the form data and update it in MongoDB Atlas
                name = request.form.get('name')
                gender = request.form.get('gender')
                student_image = request.files.get('student_image')
                tag_id = request.form.get('tag_id')
                filename = 'student_avatar.png' 
                if student_image:
                    filename = secure_filename(student_image.filename)
                    image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                    student_image.save(image_path)

                # Update student image filename in the database
                update_payload = {
                    "dataSource": "Cluster0",
                    "database": database_name,
                    "collection": collection_name,
                    "filter": {"student_id": student_id},
                    "update": {"$set": {"student_image": filename, "user_name": name, "gender": gender, "tag_id":tag_id}}
                }

                update_response = requests.post(
                    f"{ATLAS_API_URL}/action/updateOne",
                    headers=headers,
                    json=update_payload
                )

                if update_response.status_code == 200:
                    return render_template('update_data.html', studentdata=studentdata.get('documents', [])[0])
                else:
                    return f"Error updating student data: {update_response.status_code}, {update_response.text}"
                        

            return render_template('update_data.html', studentdata=studentdata.get('documents', [])[0])
        else:
            return f"Error fetching student data: {fetch_response.status_code}, {fetch_response.text}"

    return redirect(url_for('auth.login'))
@students_bp.route('/students/view/<string:student_id>',methods=['GET'])
def view_student(student_id):
    ATLAS_API_URL = current_app.config['ATLAS_API_URL']
    database_name = current_app.config['DATABASE_NAME']
    collection_name = current_app.config['COLLECTION_NAME']
    headers = current_app.config['HEADERS']
    # return f"Viewing student with ID: {student_id}"
    response = requests.post(
        f"{ATLAS_API_URL}/action/findOne",
        headers=headers,
        json={
            "database": database_name,
            "collection": collection_name,
            "dataSource": "Cluster0",
            "filter":{"student_id": student_id}
        }
    )
    
    if response.status_code == 200:
        history=get_student_attendance_history(student_id)
        student_id = response.json().get('document', {})
        return render_template('view.html', data=student_id,history=history)
    else:
        return f"Error fetching attendance data. Status code: {response.status_code}, {student_id}"

@students_bp.route('/students/delete/<string:student_id>',methods=['GET'])
def delete_student(student_id):
    ATLAS_API_URL = current_app.config['ATLAS_API_URL']
    database_name = current_app.config['DATABASE_NAME']
    collection_name = current_app.config['COLLECTION_NAME']
    headers = current_app.config['HEADERS']
    response = requests.post(
        f"{ATLAS_API_URL}/action/deleteOne",
        headers=headers,
        json={
            "database": database_name,
            "collection": collection_name,
            "dataSource": "Cluster0",
            "filter":{"student_id": student_id}
        }
    )
    if response.status_code == 200:
        flash('Record successfully deleted', 'success')
        return redirect(url_for('students.display_students'))
    else:
        return f"Error Not Deleted. Status code: {response.status_code}, {student_id}"

"""Get History"""
def get_student_attendance_history(student_id):

    ATLAS_API_URL = current_app.config['ATLAS_API_URL']
    database_name = current_app.config['DATABASE_NAME']
    headers = current_app.config['HEADERS']
    #this response is for getting tag_id
    response = requests.post(
        f"{ATLAS_API_URL}/action/findOne",
        headers=headers,
        json={
            "database": database_name,
            "collection": "students",
            "dataSource": "Cluster0",
            "filter":{"student_id": student_id}
        }
    )
    tag_id=response.json().get('document',{})
    
    if tag_id:
        tag_id = tag_id.get('tag_id', None)
    response_ = requests.post(
        f"{ATLAS_API_URL}/action/find",
        headers=headers,
        json={
            "database": database_name,
            "collection": "attendance",
            "dataSource": "Cluster0",
            "filter":{"tag_id": tag_id}
        }
    )
    if response_.status_code == 200:
        history = response_.json().get('documents', [])
        return history
    else:
        return f"Error fetching attendance data. Status code: {response_.status_code}, {student_id}"
    return history
@students_bp.route('/students/report')
def report():
    display_students()
    data = [record.get('user_name') for record in student_data]
    pdf_bytes = generate_pdf(data)

    # Send the PDF as a response
    response = Response(pdf_bytes, content_type='application/pdf')
    response.headers['Content-Disposition'] = 'inline; filename=exported_list.pdf'
    return response
def generate_pdf(data_list):
    # Create a PDF document
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer)

    # Set up PDF content
    pdf.drawString(100, 800, "Exported List:")
    
    y_position = 780
    for item in data_list:
        y_position -= 20
        pdf.drawString(120, y_position, item)

    pdf.save()
    buffer.seek(0)

    return buffer.read()

templates/attend.html
{% extends "base.html" %}

{% block title %}Attend{% endblock %}

{% block content %}
<section class="section">
  <div class="pagetitle">
    <h1>Set Attend</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/dashboard">Home</a></li>
        <li class="breadcrumb-item active">Set Attend</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Scan Your Card</h5>
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      <div class="text-center mb-4">
        <img src="{{ url_for('static', filename='assets/img/scan.png')}}" class="img-fluid" width="25%" height="25%" alt="RFID Scan Image">
      </div>
      
      <form method="POST" action="/attend">
        <div class="mb-3">
          <label for="tag_data" class="form-label">Student Tag:</label>
          <input type="text" class="form-control" id="tag_data" name="tag_data" required placeholder="Enter student tag">
        </div>

        <div class="text-center">
          <button type="submit" class="btn btn-primary">Attend</button>
        </div>
      </form>
    
    </div>
  </div>
</section>
{% endblock %}

templates/attendance.html
{% extends "base.html" %}

{% block title %}Attendance - App{% endblock %}

{% block content %}
<div class="pagetitle">
    <h1>Data Tables</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/dashboard">Home</a></li>
        <li class="breadcrumb-item active">Attendance</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->
    <div class="card">
        <div class="card-body">
    <!-- Display attendance data as a table -->
            <div class="container">
                <h5  class="card-title">Attendance</h5>
                <table class="table">
                    <thead>
                        <tr>
                            <th>TAG ID</th>
                            <th>Name</th>
                            <th>Employee ID</th>
                            <th>Timestamp</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for record in data %}
                            <tr>
                                <td>{{ record.tag_data }}</td>
                                <td>{{ record.user_name }}</td>
                                <td>{{ record.employee_id }}</td>
                                <td>{{ record.attendance_time }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock %} - Attendance</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='assets/img/favicon.png')}}" rel="icon">
  <link href="{{ url_for('static', filename='assets/img/apple-touch-icon.png')}}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/dropzone@5.9.3/dist/min/dropzone.min.css">
  <script src="https://cdn.jsdelivr.net/npm/dropzone@5.9.3/dist/min/dropzone.min.js"></script>
  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/quill/quill.snow.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/quill/quill.bubble.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/remixicon/remixicon.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/simple-datatables/style.css') }}" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='assets/css/style.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/css/custom.css') }}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/style.css') }}">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{{url_for('dashboard.dashboard')}}" class="logo d-flex align-items-center">
        <!-- <img src="{{ url_for('static', filename='assets/img/logo.png')}}" alt=""> -->
        <span class="d-none d-lg-block">Attendance</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{{ url_for('static', filename='assets/img/profile-img.jpg')}}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{session['username']}}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li>
              <a class="dropdown-item d-flex align-items-center" href="{{url_for('auth.logout')}}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="{{url_for('dashboard.dashboard')}}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Manage Attendance</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="/attend">
              <i class="bi bi-circle"></i><span>Set Attend</span>
            </a>
          </li>

        </ul>
      </li><!-- End Components Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-journal-text"></i><span>Manage Students</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{{ url_for('set_data.set_data') }}">
              <i class="bi bi-circle"></i><span>Add Student</span>
            </a>
          </li>
          <li>
            <a href="{{ url_for('students.display_students') }}">
              <i class="bi bi-circle"></i><span>Student's List</span>
            </a>
          </li>
        </ul>
      </li><!-- End Forms Nav -->
    </ul>

  </aside><!-- End Sidebar-->
  <div class="content">
    <main id="main" class="main">
    {% block content %}{% endblock %}
    </main>
  </div>
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
          &copy; Copyright <strong><span>FSAAM</span></strong>. All Rights Reserved
        </div>
      </footer><!-- End Footer -->
    
      <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    
      <!-- Vendor JS Files -->
      <script src="{{ url_for('static', filename='assets/vendor/apexcharts/apexcharts.min.js')}}"></script>
      <script src="{{ url_for('static', filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
      <script src="{{ url_for('static', filename='assets/vendor/chart.js/chart.umd.js')}}"></script>
      <script src="{{ url_for('static', filename='assets/vendor/echarts/echarts.min.js')}}"></script>
      <script src="{{ url_for('static', filename='assets/vendor/quill/quill.min.js')}}"></script>
      <script src="{{ url_for('static', filename='assets/vendor/simple-datatables/simple-datatables.js')}}"></script>
      <script src="{{ url_for('static', filename='assets/vendor/tinymce/tinymce.min.js')}}"></script>
      <script src="{{ url_for('static', filename='assets/vendor/php-email-form/validate.js')}}"></script>
    
      <!-- Template Main JS File -->
      <script src="{{ url_for('static', filename='assets/js/main.js')}}"></script>
    </body>
    </html>

templates/set_data.html
{% extends "base.html" %}

{% block title %}Add Student{% endblock %}

{% block content %}
<section class="section">
    <div class="pagetitle">
        <h1>Add Student</h1>
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/dashboard">Home</a></li>
            <li class="breadcrumb-item active">Add Student</li>
          </ol>
        </nav>
      </div><!-- End Page Title -->
  <div class="card">
      <div class="card-body">
          <h5 class="card-title">Student Form</h5>

          <!-- Vertical Form -->
          <form method="POST" action="/set-data" enctype="multipart/form-data">
                <!-- Image Upload -->
                <div class="text-center">
                    <label for="student_image" class="form-label">Student Image:</label>
                    <input type="file" class="form-control" id="student_image" name="student_image" accept="image/*">
                </div>
                <div class="col-12">
                    <label for="tag_id" class="form-label">Tag ID:</label>
                    <input type="text" class="form-control" id="tag_id" name="tag_id" required>
                </div>
              <div class="col-12">
                  <label for="student_id" class="form-label">Student ID:</label>
                  <input type="text" class="form-control" id="student_id" name="student_id" required>
              </div>
              <div class="col-12">
                  <label for="name" class="form-label">Name:</label>
                  <input type="text" class="form-control" id="name" name="name" required>
              </div>
              <div class="col-12">
                <label for="gender" class="form-label">Gender:</label>
                <select class="form-select" id="gender" name="gender" required>
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                </select>
            </div>
              <div class="text-center">
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <button type="reset" class="btn btn-secondary">Reset</button>
              </div>
          </form><!-- Vertical Form -->

      </div>
  </div>
</section>

    {% endblock %}